version = "1.1.13"

[format]
dedup = false 
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}{delim}"
client_active = "{icon}"
workspace = "{id}{delim}{clients}"
workspace_empty = "{id}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

[title_in_class."virt-manager"]
"(?i)Win" = ""
"(?i)Ubuntu" = ""
"(?i)Endeavour" = ""
"(?i)Arch" = "󰣇"
"(?i)Debian" = ""
"(?i)Alma" = ""

[class_active]
DEFAULT="{icon}"
"(?i)firefox" = " "

# [initial_title_in_class."kitty"]
# "zsh" = ""


[title_in_class."(firefox|chrom.*|Brave)"]
"(?i)Youtube" = ""
"(?i)Twitch" = ""
"(?i)Instagram" = ""
"(?i)Messenger" = ""
"(?i)Moodle" = "󱨠"

[title_in_class."(?i)kitty"]
nvim = "" 

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[class]
DEFAULT = ""
blueman-manager = ""
"(?i)firefox" = ""
"(?i)kitty" = ""
vesktop = ""
chromium = ""
Brave = ""
obs = ""
discord = ""
libreoffice-calc = "󱎏"
libreoffice-impress = "󱎐"
libreoffice-startcenter = "󰏆"
libreoffice-writer = ""
nm-connection-editor = ""
"org.pwmt.zathura" = ""
pavucontrol = ""
spotify = ""
steam = ""
virt-manager = ""
vlc = ""
Nautilus = ""
mpv = ""
"org.kde.kdenlive" = ""
"org.qbittorrent.qBittorrent" = ""
Kuro = ""
eog = ""
"org.gnome.Calculator" = ""
[exclude]
"" = "^$"
