version = "1.1.13"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}{delim}"
client_active = "{icon}"
workspace = "{id}{delim}{clients}"
workspace_empty = "{id}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
# [title_in_class."(?i)foot"]
# "emerge: (.+?/.+?)-.*" = "{match1}"

# [initial_title_in_class."kitty"]
# "zsh" = ""

# [title_in_class."(firefox|chrom|brave)"]
# "(?i)Youtube" = "󰗃"
# "(?i)twitch" = ""
# "(?i)Instagram" = ""
# "(?i)Messenger" = ""

[class_active]
DEFAULT="{icon}"
"(?i)firefox" = " "

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
# [title_in_class."(?i)foot"]
# "emerge: (.+?/.+?)-.*" = "{match1}"

# [initial_title_in_class."kitty"]
# "zsh" = ""


[title_in_class."(firefox|chrom.*|Brave)"]
"(?i)Youtube" = "<span color='#FF0000'>󰗃</span>"
"(?i)Twitch" = "<span color='purple'></span>"
"(?i)Instagram" = ""
"(?i)Messenger" = "<span color='#006AFF'></span>"
"(?i)Moodle" = "󱨠"

[title_in_class."(?i)kitty"]
nvim = "<span color='green'></span>" 

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[class]
DEFAULT = ""
blueman-manager = ""
"(?i)firefox" = ""
"(?i)kitty" = ""
vesktop = ""
chromium = ""
Brave = ""
obs = ""
discord = ""
obsidian = ""
libreoffice-calc = "󱎏"
libreoffice-impress = "󱎐"
libreoffice-startcenter = "󰏆"
libreoffice-writer = ""
nm-connection-editor = ""
"org.pwmt.zathura" = ""
pavucontrol = ""
spotify = ""
steam = ""
virt-manager = ""
vlc = ""
Nautilus = ""


[exclude]
"" = "^$" # prevent displaying clients with empty class
